version: '3.8'

services:
  spark:
    build: .
    ports:
      - "4040:4040"  # Expose Spark UI port
      - "7077:7077"  # Expose Spark master port
      - "8080:8080"  # Expose Spark master web UI
      - "8081:8081"  # Expose Spark worker web UI
    volumes:
      - ./data:/app/data  # If you have data to process, map a local directory to the container
    environment:
      SPARK_MASTER_URL: spark://spark:7077
    command: ["/bin/bash", "/app/start-spark.sh"]  # Customize this if you have different startup needs
